language: elixir
elixir:
  - "1.9"
  - "1.8"
  - "1.7" 
otp_release:
  - "22.3"
  - "21.2"
  - "17.3"
env:
  - MIX_ENV=test
script: mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
